//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping.Models.Siniflar
{
    using System;
    using System.Collections.Generic;
    
    public partial class mahalle
    {
        public int ID { get; set; }
        public string mahalle1 { get; set; }
        public Nullable<int> mahalleId { get; set; }
        public Nullable<int> ilceId { get; set; }
        public Nullable<int> ilId { get; set; }
    }
}
